import type { InvoiceData } from './types'

const today = new Date()
const due = new Date(today)
due.setDate(due.getDate() + 30)
const dateValue = (date: Date) => date.toISOString().slice(0, 10)

export const createDefaultDocument = (): InvoiceData => ({
  kind: 'invoice',
  language: 'fr',
  template: 'modern',
  logo: '',
  logoPosition: 'left',
  logoSize: 54,
  accentColor: '#2563eb',
  documentTitle: '',
  businessName: 'Studio Atlas',
  businessEmail: 'bonjour@studioatlas.ma',
  businessPhone: '+212 6 00 00 00 00',
  businessAddress: '12, rue des Orangers\nCasablanca, Maroc',
  businessTaxId: 'ICE : 001234567890123',
  businessRegistry: 'IF : 12345678 - RC : 98765 - Patente : 45678910',
  bankDetails: 'RIB : 000 000 0000000000000000 00',
  clientName: 'Maison Lumiere',
  clientEmail: 'contact@maisonlumiere.fr',
  clientAddress: '24 avenue Victor Hugo\n75016 Paris, France',
  documentNumber: `FAC-${today.getFullYear()}-001`,
  issueDate: dateValue(today),
  dueDate: dateValue(due),
  currency: 'MAD',
  taxRate: 20,
  discount: 0,
  paidAmount: 0,
  items: [
    { id: crypto.randomUUID(), description: 'Identite visuelle et direction artistique', quantity: 1, price: 8500 },
    { id: crypto.randomUUID(), description: 'Declinaisons supports digitaux', quantity: 3, price: 1200 },
  ],
  notes: 'Merci pour votre confiance. Pour toute question concernant ce document, contactez-nous par e-mail.',
  paymentTerms: 'Paiement par virement bancaire sous 30 jours.',
  footerText: '',
  signatureLabel: 'Signature et cachet',
  options: {
    showTax: true,
    showDiscount: true,
    showPaidAmount: true,
    showBankDetails: true,
    showLegalIds: true,
    showSignature: true,
  },
})

export const dictionary = {
  fr: {
    invoice: 'FACTURE',
    quote: 'DEVIS',
    from: 'Émetteur',
    billTo: 'Client',
    number: 'Numéro',
    issued: 'Date d’émission',
    due: 'Échéance',
    validUntil: 'Valable jusqu’au',
    description: 'Description',
    qty: 'Qté',
    unitPrice: 'Prix unitaire',
    amount: 'Montant',
    subtotal: 'Sous-total',
    discount: 'Remise',
    tax: 'TVA',
    total: 'Total TTC',
    paid: 'Déjà payé',
    balance: 'Solde du',
    quoteTotal: 'Total devis',
    notes: 'Notes',
    payment: 'Conditions',
    bank: 'Coordonnees bancaires',
    signature: 'Signature',
  },
  en: {
    invoice: 'INVOICE',
    quote: 'QUOTE',
    from: 'From',
    billTo: 'Client',
    number: 'Number',
    issued: 'Issue date',
    due: 'Due date',
    validUntil: 'Valid until',
    description: 'Description',
    qty: 'Qty',
    unitPrice: 'Unit price',
    amount: 'Amount',
    subtotal: 'Subtotal',
    discount: 'Discount',
    tax: 'Tax',
    total: 'Total',
    paid: 'Paid',
    balance: 'Balance due',
    quoteTotal: 'Quote total',
    notes: 'Notes',
    payment: 'Terms',
    bank: 'Bank details',
    signature: 'Signature',
  },
}
